Remember interactor name and action arguments
thefrontside/interactors pull request #197
Opened 2022-03-30 07:29 UTC by jnicklas

## Motivation

In order to enable remote interactors (see #178), we need to track more information about the interactions themselves. This adds the arguments to an interaction, as well as the name of the interactor to the public information that can be reflected upon.

## Approach

Expose these as part of the public API

2022-04-05 12:41 UTC, cowboyd approved these changes
Looks great to me, and the more reflective the better!

2022-04-05 12:42 UTC, cowboyd requested changes
Oops, looks like we need a changeset though.

2022-04-07 08:46 UTC, jnicklas commented
Changeset added :)

2022-04-07 11:45 UTC, cowboyd approved these changes
🚀📯 🤘

2022-04-08 19:43 UTC, merged